pevam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('pevams.urls'))
]

pevams/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('policial/', views.policial, name='policial'),
    path('policial/<int:pk>/edit/', views.edit_policial, name='edit_policial'),
    path('policial/<int:pk>/delete/', views.delete_policial, name='delete_policial'),
    path('hospital/', views.hospital, name='hospital'),
    path('hospital/<int:pk>/edit/', views.edit_hospital, name='edit_hospital'),
    path('hospital/<int:pk>/delete/', views.delete_hospital, name='delete_hospital'),
    path('contato_emergencia/', views.contato_emergencia, name='contato_emergencia'),
    path('local/', views.local, name="local"),
    path('pevam/', views.criar_pevam, name='criar_pevam'),
    path('policial/list/', views.list_policial, name='list_policial'),
    path('hospital/list/', views.list_hospital, name='list_hospital'),
	
    path('cadastro_agente/', views.cadastro_agente, name='cadastro_agente'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

pevams/models.py
from django.db import models
from django.contrib.auth.models import User

class Policial(models.Model):
    TIPO_SANGUE_CHOICES = [
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    ]

    numero_registro = models.CharField(max_length=20)
    nome = models.CharField(max_length=100)
    lotacao = models.CharField(max_length=100)
    tipo_sanguineo = models.CharField(max_length=50, choices=TIPO_SANGUE_CHOICES)
    plano_saude = models.CharField(max_length=100)
    numero_plasau = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

class ContatoEmergencia(models.Model):
    policial = models.OneToOneField(Policial, on_delete=models.CASCADE, related_name='contato_emergencia')
    nome_contato = models.CharField(max_length=100)
    celular_contato = models.CharField(max_length=15)
    email_contato = models.CharField(max_length=50)

    def __str__(self):
        return self.nome_contato
    
class Local(models.Model):
    logradouro = models.CharField(max_length=100)
    numero = models.CharField(max_length=5)
    complemento = models.CharField(max_length=15, blank=True, null=True)
    bairro = models.CharField(max_length=25)
    cidade = models.CharField(max_length=50)
    cep = models.CharField(max_length=8)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.logradouro
    
class Hospital(models.Model):
    TIPO_ENTRADA_CHOICES = [
        ('porta aberta', 'porta aberta'),
        ('necessita regulação', 'necessita regulação'),
    ]
    nome = models.CharField(max_length=100)
    logradouro = models.CharField(max_length=100)
    numero = models.CharField(max_length=5)
    complemento = models.CharField(max_length=15, blank=True, null=True)
    bairro = models.CharField(max_length=25)
    cidade = models.CharField(max_length=50)
    cep = models.CharField(max_length=8)
    latitude = models.FloatField()
    longitude = models.FloatField()
    telefone = models.CharField(max_length=16)
    forma_entrada = models.CharField(max_length=50, choices=TIPO_ENTRADA_CHOICES)

    def __str__(self):
        return self.nome

class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


pevams/forms.py
from django import forms
from .models import Policial, ContatoEmergencia, Hospital
from django.forms import inlineformset_factory

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class PolicialForm(forms.ModelForm):
    class Meta:
        model = Policial
        fields = ['numero_registro', 'nome', 'lotacao', 'tipo_sanguineo', 'plano_saude', 'numero_plasau']

class ContatoEmergenciaForm(forms.ModelForm):
    class Meta:
        model = ContatoEmergencia
        fields = ['nome_contato', 'celular_contato', 'email_contato']

class HospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['nome', 'logradouro', 'numero', 'complemento', 'bairro', 'cidade', 'cep', 'latitude', 'longitude', 'telefone', 'forma_entrada']

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label="Usuário", max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="Senha", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="Confirme a Senha", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

pevams/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Policial, Local, Hospital, ContatoEmergencia
from .forms import PolicialForm, ContatoEmergenciaForm, HospitalForm
from .geocoding import get_geocode
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm

from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
import qrcode
import io
import base64
from django.contrib.auth.decorators import login_required


def cadastro_agente(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = CustomUserCreationForm()
    return render(request, 'sections/cadastro_agente.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('realizados')  # Página de destino após o login
            else:
                error_message = "Usuário ou senha incorretos. Por favor, tente novamente."
                return render(request, 'sections/login.html', {'form': form, 'error_message': error_message})
        else:
            error_message = "Formulário inválido. Por favor, tente novamente."
            return render(request, 'sections/login.html', {'form': form, 'error_message': error_message})
    else:
        form = AuthenticationForm()

    return render(request, 'sections/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login_view')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')  # Redirect to home or another page after login
    else:
        form = AuthenticationForm()

    return render(request, 'sections/login.html', {'form': form})

@login_required(login_url='login_view')
def home(request):
    return render(request, 'sections/home.html', {'is_homepage': True})

@login_required(login_url='login_view')
def policial(request):
    if request.method == 'POST':
        form_data = request.POST

        policial = Policial(
            numero_registro=form_data['numero_registro'],
            nome=form_data['nome'],
            lotacao=form_data['lotacao'],
            tipo_sanguineo=form_data['tipo_sanguineo'],
            plano_saude=form_data['plano_saude'],
            numero_plasau=form_data['numero_plasau']
        )
        policial.save()

        contato_emergencia = ContatoEmergencia(
            policial=policial,
            nome_contato=form_data['nome_contato'],
            celular_contato=form_data['celular_contato'],
            email_contato=form_data['email_contato']
        )
        contato_emergencia.save()

        return redirect('list_policial')

    return render(request, 'sections/policial.html', {'is_homepage': False})

@csrf_exempt
@login_required(login_url='login_view')
def contato_emergencia(request):
    if request.method == 'POST':
        policial_id = request.POST.get('policial_id')
        
        if not policial_id:
            return JsonResponse({'status': 'error', 'message': 'Cadastro ID não enviado.'})

        try:
            policial = Policial.objects.get(id=policial_id)
        except Policial.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Cadastro não encontrado.'})

        form = ContatoEmergenciaForm(request.POST)
        
        if form.is_valid():
            contato_emergencia = form.save(commit=False)
            contato_emergencia.policial = policial
            contato_emergencia.save()
            return JsonResponse({'status': 'success', 'message': 'Contato de emergência cadastrado com sucesso!'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Dados incompletos ou inválidos.'})

    return JsonResponse({'status': 'error', 'message': 'Método inválido.'})

@login_required(login_url='login_view')
def local(request):
    if request.method == "POST":
        logradouro = request.POST.get("logradouro")
        numero = request.POST.get("numero")
        complemento = request.POST.get("complemento", "")
        bairro = request.POST.get("bairro")
        cidade = request.POST.get("cidade")
        cep = request.POST.get("cep")
        latitude = request.POST.get("latitude")
        longitude = request.POST.get("longitude")

        local = Local(
            logradouro=logradouro,
            numero=numero,
            complemento=complemento,
            bairro=bairro,
            cidade=cidade,
            cep=cep,
            latitude=float(latitude),
            longitude=float(longitude)
        )
        local.save()

        return JsonResponse({"success": True, "message": "Endereço salvo com sucesso!"})
    else:
        return render(request, 'sections/local.html', {'is_homepage': False})

@login_required(login_url='login_view')
def hospital(request):
    if request.method == "POST":
        nome = request.POST.get("nome")
        logradouro = request.POST.get("logradouro")
        numero = request.POST.get("numero")
        complemento = request.POST.get("complemento", "")
        bairro = request.POST.get("bairro")
        cidade = request.POST.get("cidade")
        cep = request.POST.get("cep")
        latitude = request.POST.get("latitude")
        longitude = request.POST.get("longitude")
        telefone = request.POST.get("telefone")
        forma_entrada = request.POST.get("forma-de-entrada")

        try:
            hospital = Hospital(
                nome=nome,
                logradouro=logradouro,
                numero=numero,
                complemento=complemento,
                bairro=bairro,
                cidade=cidade,
                cep=cep,
                latitude=float(latitude),
                longitude=float(longitude),
                telefone=telefone,
                forma_entrada=forma_entrada
            )
            hospital.save()
            messages.success(request, 'Hospital cadastrado com sucesso!')
            return redirect('list_hospital')
        except Exception as e:
            messages.error(request, f'Erro ao cadastrar hospital: {e}')
    
    return render(request, 'sections/hospital.html', {'is_homepage': False})


@login_required(login_url='login_view')
def edit_policial(request, pk):
    policial = get_object_or_404(Policial, pk=pk)
    contato_emergencia = getattr(policial, 'contato_emergencia', None)
    
    if request.method == 'POST':
        form = PolicialForm(request.POST, instance=policial)
        contato_form = ContatoEmergenciaForm(request.POST, instance=contato_emergencia)

        if form.is_valid() and contato_form.is_valid():
            form.save()
            contato = contato_form.save(commit=False)
            contato.policial = policial  # Link the contact to the policial
            contato.save()
            return redirect('list_policial')
    else:
        form = PolicialForm(instance=policial)
        contato_form = ContatoEmergenciaForm(instance=contato_emergencia)
    
    return render(request, 'sections/edit_policial.html', {'form': form, 'contato_form': contato_form})

@login_required(login_url='login_view')
def delete_policial(request, pk):
    policial = get_object_or_404(Policial, pk=pk)
    if request.method == 'POST':
        policial.delete()
        return redirect('list_policial')
    return render(request, 'sections/delete_confirm.html', {'object': policial, 'type': 'Policial'})

@login_required(login_url='login_view')
def edit_hospital(request, pk):
    hospital = get_object_or_404(Hospital, pk=pk)
    if request.method == 'POST':
        form = HospitalForm(request.POST, instance=hospital)
        if form.is_valid():
            form.save()
            return redirect('list_hospital')
    else:
        form = HospitalForm(instance=hospital)
    return render(request, 'sections/edit_hospital.html', {'form': form, 'hospital': hospital})

@login_required(login_url='login_view')
def delete_hospital(request, pk):
    hospital = get_object_or_404(Hospital, pk=pk)
    if request.method == 'POST':
        hospital.delete()
        return redirect('list_hospital')
    return render(request, 'sections/delete_confirm.html', {'object': hospital, 'type': 'Hospital'})

@login_required(login_url='login_view')
def list_policial(request):
    policiais = Policial.objects.all()
    return render(request, 'sections/list_policial.html', {'policiais': policiais})

@login_required(login_url='login_view')
def list_hospital(request):
    hospitals = Hospital.objects.all()
    return render(request, 'sections/list_hospital.html', {'hospitals': hospitals})


@login_required(login_url='login_view')
def criar_pevam(request):
    if request.method == 'POST':
        endereco = request.POST.get('endereco')

pevams/templates/sections/cadastrar_evento_critico.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>CADASTRAR <strong>EVENTO CRÍTICO</strong></h1>
    <form id="cadastrarEventoForm">
        {% csrf_token %}
        
        <div class="mb-3 row">
            <label for="id_tipo_evento" class="col-sm-2 col-form-label"><strong>TIPO DE EVENTO CRÍTICO</strong></label>
            <div class="col-sm-4">
                <select id="id_tipo_evento" name="tipo_evento" class="form-select" required>
                    <option value="" disabled selected>Escolha um tipo de evento</option>
                    <option value="acidente">Acidente</option>
                    <option value="incendio">Incêndio</option>
                    <option value="emergencia_medica">Emergência Médica</option>
                </select>
            </div>
        </div>
        
        <div class="mb-3 row">
            <div class="col-sm-4 offset-sm-2 text-end">
                <button type="submit" class="btn btn-danger">CADASTRAR</button>
            </div>
        </div>
    </form>

    <!-- Mensagem de sucesso/erro -->
    <div id="mensagem" class="mt-3"></div>
</div>

<script>
    document.getElementById('cadastrarEventoForm').addEventListener('submit', function(e) {
        e.preventDefault();  // Evita o recarregamento da página

        const formData = new FormData(this);  // Coleta os dados do formulário

        fetch('{% url "cadastrar_evento_critico" %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',  // Adiciona o token CSRF ao cabeçalho
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                Swal.fire({
                    icon: 'success',
                    title: 'Sucesso!',
                    text: 'Evento crítico cadastrado com sucesso!',
                    confirmButtonText: 'Ok'
                });
            } else {
                Swal.fire({
                    icon: 'error',
                    title: 'Erro!',
                    text: data.message || 'Erro ao cadastrar evento crítico.',
                    confirmButtonText: 'Ok'
                });
            }
        })
        .catch(error => {
            console.error('Erro:', error);
            Swal.fire({
                icon: 'error',
                title: 'Erro!',
                text: 'Erro ao cadastrar evento crítico. Por favor, tente novamente.',
                confirmButtonText: 'Ok'
            });
        });
    });
</script>
{% endblock %}

pevams/templates/sections/cadastrar_lotacao.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>CADASTRAR <strong>LOTAÇÃO</strong></h1>
    <form id="cadastrarLotacaoForm">
        {% csrf_token %}
        
        <div class="mb-3 row">
            <label for="id_nome" class="col-sm-2 col-form-label"><strong>LOTAÇÃO</strong></label>
            <div class="col-sm-4">
                {{ form.nome }}
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-sm-4 offset-sm-2 text-end">
                <button type="submit" class="btn btn-danger">CADASTRAR</button>
            </div>
        </div>
    </form>

    <!-- Mensagem de sucesso/erro -->
    <div id="mensagem" class="mt-3"></div>
</div>

<script>
    document.getElementById('cadastrarLotacaoForm').addEventListener('submit', function(e) {
        e.preventDefault();  // Evita o recarregamento da página

        const formData = new FormData(this);  // Coleta os dados do formulário

        fetch('{% url "cadastrar_lotacao" %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',  // Adiciona o token CSRF ao cabeçalho
            }
        })
        .then(response => response.json())
        .then(data => {
            const mensagemDiv = document.getElementById('mensagem');
            if (data.status === 'success') {
                mensagemDiv.innerHTML = `<div class="alert alert-success">${data.message}</div>`;
            } else {
                mensagemDiv.innerHTML = `<div class="alert alert-danger">Erro: ${data.errors.nome[0]}</div>`;
            }
        })
        .catch(error => {
            console.error('Erro:', error);
            document.getElementById('mensagem').innerHTML = `<div class="alert alert-danger">Erro ao cadastrar lotação.</div>`;
        });
    });
</script>
{% endblock %}

pevams/templates/sections/cadastro.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>CADASTRAR <strong>PESSOA</strong></h1>
    <form id="cadastroPessoaForm">
        {% csrf_token %}
        
        <div class="mb-3 row">
            <label for="id_numero_registro" class="col-sm-2 col-form-label"><strong>N° REGISTRO</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_numero_registro" name="numero_registro" class="form-control"
                    placeholder="10.001" required>
            </div>
        </div>
        
        <div class="mb-3 row">
            <label for="id_nome" class="col-sm-2 col-form-label"><strong>NOME</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_nome" name="nome" class="form-control" placeholder="João da Silva" required>
            </div>
        </div>
        
        <div class="mb-3 row">
            <label for="id_lotacao" class="col-sm-2 col-form-label"><strong>LOTAÇÃO</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_lotacao" name="lotacao" class="form-control"
                    placeholder="DELEGACIA DE CAMPINAS" required>
            </div>
        </div>
        
        <div class="mb-3 row">
            <label for="id_tipo_sanguineo" class="col-sm-2 col-form-label"><strong>TIPO SANGUÍNEO</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_tipo_sanguineo" name="tipo_sanguineo" class="form-control"
                    placeholder="A+" required>
            </div>
        </div>
        
        <div class="mb-3 row">
            <label for="id_plano_saude" class="col-sm-2 col-form-label"><strong>PLANO DE SAÚDE</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_plano_saude" name="plano_saude" class="form-control"
                    placeholder="UNIMED" required>
            </div>
        </div>
        
        <div class="mb-3 row">
            <div class="col-sm-4 offset-sm-2 text-end">
                <button type="submit" class="btn btn-danger">CADASTRAR</button>
            </div>
        </div>
    </form>

    <!-- Mensagem de sucesso/erro -->
    <div id="mensagem" class="mt-3"></div>
</div>

<script>
    document.getElementById('cadastroPessoaForm').addEventListener('submit', function(e) {
        e.preventDefault();  // Evita o recarregamento da página
        console.log("Formulário enviado");

        const formData = new FormData(this);  // Coleta os dados do formulário

        fetch('{% url "cadastro" %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',  // Adiciona o token CSRF ao cabeçalho
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                Swal.fire({
                    icon: 'success',
                    title: 'Sucesso!',
                    text: 'Pessoa cadastrada com sucesso!',
                    confirmButtonText: 'Ok'
                }).then(() => {
                    // Aqui, após o cadastro, chama o cadastro do contato de emergência
                    cadastrarContatoEmergencia(data.cadastro_id);
                });
            } else {
                Swal.fire({
                    icon: 'error',
                    title: 'Erro!',
                    text: data.message || 'Erro ao cadastrar pessoa.',
                    confirmButtonText: 'Ok'
                });
            }
        })
        .catch(error => {
            console.error('Erro:', error);
            Swal.fire({
                icon: 'error',
                title: 'Erro!',
                text: 'Erro ao cadastrar pessoa. Por favor, tente novamente.',
                confirmButtonText: 'Ok'
            });
        });
    });

    function cadastrarContatoEmergencia(cadastroId) {
        Swal.fire({
            title: 'Cadastrar Contato de Emergência',
            html: `
                <input type="text" id="nome_contato" class="swal2-input" placeholder="Nome do Contato">
                <input type="text" id="telefone_contato" class="swal2-input" placeholder="Telefone do Contato">
            `,
            focusConfirm: false,
            preConfirm: () => {
                const nomeContato = document.getElementById('nome_contato').value;
                const telefoneContato = document.getElementById('telefone_contato').value;

                const contatoData = new FormData();
                contatoData.append('cadastro_id', cadastroId);
                contatoData.append('nome_contato', nomeContato);
                contatoData.append('telefone_contato', telefoneContato);

                return fetch('{% url "contato_emergencia" %}', {
                    method: 'POST',
                    body: contatoData,
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status !== 'success') {
                        throw new Error(data.message || 'Erro ao cadastrar contato de emergência.');
                    }
                });
            }
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire({
                    icon: 'success',
                    title: 'Sucesso!',
                    text: 'Contato de emergência cadastrado com sucesso!',
                    confirmButtonText: 'Ok'
                });
            }
        }).catch((error) => {
            Swal.fire({
                icon: 'error',
                title: 'Erro!',
                text: error.message,
                confirmButtonText: 'Ok'
            });
        });
    }
</script>
{% endblock %}

pevams/templates/sections/cadastro_agente.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container-fluid" style="height: calc(100vh - 60px);">
    <div class="container d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6">
            <h1 class="text-center mb-4 ms-5">CADASTRAR <strong>USUÁRIO</strong></h1>
            
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <form method="post" novalidate>
                {% csrf_token %}

                <div class="row mb-3 align-items-center">
                    <label for="{{ form.username.id_for_label }}" class="col-12 col-sm-4 col-form-label text-sm-end mb-2 mb-sm-0"><strong>Usuário</strong></label>
                    <div class="col-12 col-sm-8">
                        {{ form.username }}
                        {% for error in form.username.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="row mb-3 align-items-center">
                    <label for="{{ form.password1.id_for_label }}" class="col-12 col-sm-4 col-form-label text-sm-end mb-2 mb-sm-0"><strong>Senha</strong></label>
                    <div class="col-12 col-sm-8">
                        {{ form.password1 }}
                        {% for error in form.password1.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="row mb-3 align-items-center">
                    <label for="{{ form.password2.id_for_label }}" class="col-12 col-sm-4 col-form-label text-sm-end mb-2 mb-sm-0"><strong>Confirme a Senha</strong></label>
                    <div class="col-12 col-sm-8">
                        {{ form.password2 }}
                        {% for error in form.password2.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-sm-4 offset-sm-2 text-end">
                        <button type="submit" class="btn btn-danger">CADASTRAR</button>
                    </div>
                </div>
        </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pevams/templates/sections/contato_emergencia.html

{% extends 'base/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>CADASTRAR <strong>CONTATO DE EMERGÊNCIA</strong></h1>
    <form id="contatoEmergenciaForm">
        {% csrf_token %}

        <div class="mb-3 row">
            <label for="id_nome_contato" class="col-sm-2 col-form-label"><strong>NOME DO CONTATO</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_nome_contato" name="nome_contato" class="form-control" placeholder="Nome do contato" required>
            </div>
        </div>

        <div class="mb-3 row">
            <label for="id_celular_contato" class="col-sm-2 col-form-label"><strong>CELULAR DO CONTATO</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_celular_contato" name="celular_contato" class="form-control" placeholder="celular do contato" required>
            </div>
        </div>

        <div class="mb-3 row">
            <label for="id_email_contato" class="col-sm-2 col-form-label"><strong>EMAIL DO CONTATO</strong></label>
            <div class="col-sm-4">
                <input type="text" id="id_email_contato" name="email" class="form-control" placeholder="email do contato" required>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-sm-4 offset-sm-2 text-end">
                <button type="submit" class="btn btn-danger">CADASTRAR</button>
            </div>
        </div>
    </form>

    <!-- Mensagem de sucesso/erro -->
    <div id="mensagem" class="mt-3"></div>
</div>

<script>
    document.getElementById('contatoEmergenciaForm').addEventListener('submit', function(e) {
        e.preventDefault();  // Evita que o formulário faça um reload na página

        const formData = new FormData(this);  // Coleta os dados do formulário

        fetch('{% url "contato_emergencia" %}', {  // Altere esta linha
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',  // Adiciona o token CSRF ao cabeçalho
            }
        })
        .then(response => response.json())
        .then(data => {
            const mensagemDiv = document.getElementById('mensagem');
            if (data.status === 'success') {
                mensagemDiv.innerHTML = `<div class="alert alert-success">${data.message}</div>`;
            } else {
                mensagemDiv.innerHTML = `<div class="alert alert-danger">${data.message}</div>`;
            }
        })
        .catch(error => {
            console.error('Erro:', error);
            document.getElementById('mensagem').innerHTML = `<div class="alert alert-danger">Erro ao cadastrar contato.</div>`;
        });
    });
</script>
{% endblock %}